### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by imapotatoes11**

### CODE REVIEW

**Comment by JmsTng** [comment]
Woah I can spam comments

**Comment by JmsTng** [comment]
Comment #2

**Comment by imapotatoes11** [comment]
oh sh- you can comment on closed prs

**Comment by imaegg11** [comment]
damn you can

**Comment by imapotatoes11** [comment]
thats crazy

**Comment by imaegg11** [comment]
do you think i can bot this

**Comment by imapotatoes11** [comment]
prob

**Comment by imapotatoes11** [comment]
acc dunno

**Comment by imapotatoes11** [comment]
might be against tos

**Comment by imaegg11** [comment]
do you think i can bot this

**Comment by imaegg11** [comment]
i can

**Comment by imaegg11** [comment]
ungabunga

**Comment by imapotatoes11** [comment]
damn

**Comment by imaegg11** [comment]
i mean tbf probs against ToS ngl

**Comment by imapotatoes11** [comment]
yes

**Comment by imaegg11** [comment]
sadge

**Comment by imaegg11** [comment]
tho i could automate it so i dont have to press the button each time

**Pull request closed without merging**
